POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username": "nikita",
    "email": "nikita@example.com",
    "password": "password123"
}


### LOGIN TEST WITH USERNAME
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "username": "nikita",
    "password": "password123"
}


### LOGING TEST WITH EMAIL
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "nikita@example.com",
    "password": "password123"
}

###

GET http://localhost:3000/api/test-auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTc2MjYzODQ4OCwiZXhwIjoxNzYzMjQzMjg4fQ.mXB9gFL9pHG8BgtnCPZ7bjHY7UiDyDxf4sG6DUZiTA8

###

GET http://localhost:3000/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTc2MjYzODQ4OCwiZXhwIjoxNzYzMjQzMjg4fQ.mXB9gFL9pHG8BgtnCPZ7bjHY7UiDyDxf4sG6DUZiTA8

###

PUT http://localhost:3000/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTc2MjYzODQ4OCwiZXhwIjoxNzYzMjQzMjg4fQ.mXB9gFL9pHG8BgtnCPZ7bjHY7UiDyDxf4sG6DUZiTA8
Content-Type: application/json

{
    "display_name": "Nikita Cool",
    "bio": "Building a messaging app with Claude!"
}

###

GET http://localhost:3000/api/users/search?q=nik
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTc2MjYzODQ4OCwiZXhwIjoxNzYzMjQzMjg4fQ.mXB9gFL9pHG8BgtnCPZ7bjHY7UiDyDxf4sG6DUZiTA8

###

GET http://localhost:3000/api/users/search
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTc2MjYzODQ4OCwiZXhwIjoxNzYzMjQzMjg4fQ.mXB9gFL9pHG8BgtnCPZ7bjHY7UiDyDxf4sG6DUZiTA8