POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username": "testuser",
    "email": "test@example.com",
    "password": "password123"
}


### LOGIN TEST WITH USERNAME
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "username": "testuser",
    "password": "password123"
}


### LOGING TEST WITH EMAIL
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "password123"
}